FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

ARG MODEL_NAME_OR_PATH="gpt2"
ARG IS_FP16="False"
ENV MODEL_NAME_OR_PATH="${MODEL_NAME_OR_PATH}"
ENV IS_FP16="${IS_FP16}"

# Install Python3
RUN apt-get update && apt-get -y install python3 python3-dev python3-pip
RUN alias pip=pip3
RUN alias python=python3

COPY ./requirements_gpu.txt ./requirements.txt
RUN pip install --upgrade -r ./requirements.txt

COPY ./huggingfaceAPI /app
WORKDIR /app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]