FROM python:3.8.10

ARG MODEL_NAME_OR_PATH="gpt2"
ENV MODEL_NAME_OR_PATH="${MODEL_NAME_OR_PATH}"

COPY ./requirements_cpu.txt /app/requirements.txt
RUN pip install --upgrade -r requirements.txt

COPY ./huggingfaceAPI /app
WORKDIR /app
