FROM python:3.8.10

ARG MODEL_NAME_OR_PATH="gpt2"
ARG IS_FP16="False"
ENV MODEL_NAME_OR_PATH="${MODEL_NAME_OR_PATH}"
ENV IS_FP16="${IS_FP16}"

COPY ./requirements_cpu.txt /app/requirements.txt
RUN pip install --upgrade -r requirements.txt

COPY ./huggingfaceAPI /app
WORKDIR /app
